//AES-256

package main

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
)

// EncryptionKey is the shared secret between the agent and the server.
// It MUST be exactly 32 bytes for AES-256.
// In a real scenario, this key should be dynamically generated by the builder.
var EncryptionKey = "Passw0rd32bytesLongSecretKey!!!!"

// Encrypt encrypts the plain text using AES-256-GCM.
// It returns a Base64 encoded string containing the nonce and the ciphertext.
func Encrypt(plaintext string) (string, error) {
	// 1. Create a new AES cipher block using the secret key
	block, err := aes.NewCipher([]byte(EncryptionKey))
	if err != nil {
		return "", err
	}

	// 2. Wrap the block in Galois Counter Mode (GCM)
	// GCM provides both encryption and authentication (integrity check).
	aesGCM, err := cipher.NewGCM(block)
	if err != nil {
		return "", err
	}

	// 3. Create a unique Nonce (Number used once)
	// Standard nonce size for GCM is 12 bytes.
	nonce := make([]byte, aesGCM.NonceSize())
	if _, err = io.ReadFull(rand.Reader, nonce); err != nil {
		return "", err
	}

	// 4. Encrypt and seal the data
	// Seal appends the encrypted data to the nonce.
	// Format: [Nonce | Ciphertext]
	ciphertext := aesGCM.Seal(nonce, nonce, []byte(plaintext), nil)

	// 5. Encode to Base64 to make it safe for HTTP transport (JSON compatible)
	return base64.StdEncoding.EncodeToString(ciphertext), nil
}

// Decrypt decrypts the Base64 encoded ciphertext using AES-256-GCM.
func Decrypt(encryptedString string) (string, error) {
	// 1. Decode the Base64 string back to bytes
	data, err := base64.StdEncoding.DecodeString(encryptedString)
	if err != nil {
		return "", err
	}

	// 2. Create the AES cipher block
	block, err := aes.NewCipher([]byte(EncryptionKey))
	if err != nil {
		return "", err
	}

	// 3. Create the GCM mode instance
	aesGCM, err := cipher.NewGCM(block)
	if err != nil {
		return "", err
	}

	// 4. Validate the data length
	// The data must be at least as long as the nonce size.
	nonceSize := aesGCM.NonceSize()
	if len(data) < nonceSize {
		return "", errors.New("ciphertext too short")
	}

	// 5. Separate Nonce and Ciphertext
	nonce, ciphertext := data[:nonceSize], data[nonceSize:]

	// 6. Decrypt and verify the data (Open)
	plaintext, err := aesGCM.Open(nil, nonce, ciphertext, nil)
	if err != nil {
		// This error occurs if the key is wrong or the data has been tampered with.
		return "", fmt.Errorf("decryption failed: %v", err)
	}

	return string(plaintext), nil
}
